services:
  backend:
    container_name: notebook-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notebook-db-danik0709061-e4f7.h.aivencloud.com:10978/defaultdb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=avnadmin
      - SPRING_DATASOURCE_PASSWORD=AVNS_MgMNspqJK5b4fIXUU1x
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped

  frontend:
    container_name: notebook-frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://back-xyz.trycloudflare.com
    depends_on:
      - backend
    restart: unless-stopped