spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/notebook_db}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bazelin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.jdbc.datasource.init=DEBUG

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.properties.hibernate.use_sql_comments=false