spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.properties.hibernate.use_sql_comments=false

logging.level.root=INFO
logging.level.dev.notebook.notebook=DEBUG
logging.level.org.hibernate.SQL=DEBUG